molgenis:
  uri: https://datashield-backend.dev.molgenis.org
  token: test

datashield:
# Allows you to override the default DataSHIELD options
#  options:
#    default:
#      nfilter:
#        string: 90

spring:
  security:
    user:
      name: admin
      password: admin
minio:
  url: http://localhost
  port: 9000
  access-key: molgenis
  secret-key: molgenis
  bucket: datashield

security:
  enable-csrf: false
