armadillo:
  oidc-permission-enabled: true
spring:
  security:
    oauth2:
      client:
        provider:
          molgenis:
            issuer-uri: @ISSUERURL@
        registration:
          molgenis:
            client-id: @CLIENTSECRET@
            client-secret: @CLIENTID@
      resourceserver:
        jwt:
          issuer-uri: @ISSUERURL@
        opaquetoken:
          client-id: @CLIENTID@
