armadillo:
  # set this true if you want Armadillo to create/edit/delete profile docker images via the user interface
  docker-management-enabled: true

  # uncomment this to configure an oidc user as admin user
  # oidc-admin-user: user@yourdomain.org

spring:
  # required to check this!
  security:
    user:
      # please change this admin password!
      password:
    ## uncomment oidc settings below to enable oidc
#    oauth2:
#      client:
#        registration:
#            molgenis:
#               client-id: 'your-client-id'
#               client-secret: 'your-client-secret'
#        provider:
#          molgenis:
#            issuer-uri: 'your-issuer-uri'
#      resourceserver:
#        jwt:
#          issuer-uri: 'http://auth.molgenis.org'
#        opaquetoken:
#          client-id: 'your-client-id'

# optional settings (review spring handbook to find more)
  servlet:
    multipart:
      ## change this if your files are bigger
      max-file-size: 1000MB
      max-request-size: 1000MB

storage:
  ## to change location of the data storage
  root-dir: data

logging:
  level:
    ## change to DEBUG to have more details, typically when developing
    org.molgenis: INFO

