molgenis:
  uri: https://datashield-backend.dev.molgenis.org
  token: test

rserve:
  port: 6311
  host: localhost

spring:
  security:
    user:
      name: admin
      password: admin

security:
  enable-csrf: false