molgenis:
  uri: https://latest.test.molgenis.org
  token: test

rserve:
  port: 6312
  host: localhost

spring:
  security:
    user:
      name: admin
      password: admin

security:
  enable-csrf: false