rserve:
  environments:
    - name: default
      host: localhost
      port: 6311
#    - name: exposome
#      host: localhost
#      port: 6312
    - name: omics
      host: localhost
      port: 6313

datashield:
  profiles:
    - name: default
      environment: default
      whitelist:
        - dsBase
      options:
        datashield:
          # the seed can only be 9 digits
          seed: 342325352
#          foo: bar
#    - name: exposome
#      environment: exposome
#      whitelist:
#        - dsBase
#        - dsExposome
    - name: omics
      environment: omics
      whitelist:
        - dsBase
        - dsOmics
        - resourcer
      options:
        datashield:
          # the seed can only be 9 digits
          seed: 712368126
#          foo: bar

springdoc:
  swagger-ui:
    enabled: false

spring:
  application:
    name: armadillo
  security:
    user:
      name: admin
      roles:
        - SU

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  error:
    include-binding-errors: always
    include-message: always

audit:
  log:
    path: logs/audit.log

logging:
  config: classpath:logback-file.xml

---
spring:
  security:
    user:
      password: admin
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://auth.molgenis.org'
        opaquetoken:
          client-id: 'b396233b-cdb2-449e-ac5c-a0d28b38f791'
  config:
    activate:
      on-profile: development

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread|%.8X{sessionID}] %-5level %logger{36} - %msg%n"
  level:
    org.molgenis: DEBUG
    org:
      springframework:
        boot:
          actuate:
            audit:
              listener:
                AuditListener: DEBUG
          web:
            context: DEBUG

minio:
  url: http://localhost
  port: 9000
  access-key: molgenis
  secret-key: molgenis

