rserve:
  environments:
    - name: default
      host: localhost
      port: 6311

datashield:
  # set this to 'true' if you want to accept permissions from oidc provider
  oidc-permission-enabled: false
  profiles:
    - name: default
      environment: default
      whitelist:
        - dsBase
      options:
        datashield:
          # the seed can only be 9 digits
          seed: 342325352
          # foo: bar

springdoc:
  swagger-ui:
    enabled: true
    operationsSorter: alpha
    csrf:
      enabled: true

spring:
  servlet:
    multipart:
      max-file-size: 20MB
  application:
    name: armadillo
  security:
    user:
      name: admin
      roles:
        - SU

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  error:
    include-binding-errors: always
    include-message: always

audit:
  log:
    path: logs/audit.log

logging:
  config: classpath:logback-file.xml

---
spring:
  security:
    user:
      password: admin
    oauth2:
      client:
        provider:
          molgenis:
            issuer-uri: 'https://auth.molgenis.org'
          #recommend to set registration via environment variables
          #in IntelliJ something like:
          #SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MOLGENIS_CLIENT-ID=b396233b-cdb2-449e-ac5c-a0d28b38f791;
          #SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MOLGENIS_CLIENT-SECRET=xxx
      resourceserver:
        jwt:
          issuer-uri: 'https://auth.molgenis.org'
        opaquetoken:
          client-id: 'b396233b-cdb2-449e-ac5c-a0d28b38f791'
  config:
    activate:
      on-profile: development

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread|%.8X{sessionID}] %-5level %logger{36} - %msg%n"
  level:
    org.molgenis: DEBUG
    org:
      springframework:
        boot:
          actuate:
            audit:
              listener:
                AuditListener: DEBUG
          web:
            context: DEBUG

storage:
  root-dir: "data"

# Uncomment the following block to enable MinIO storage (overrules local storage)
#minio:
#  url: http://localhost
#  port: 9000
#  access-key: molgenis
#  secret-key: molgenis

---
spring:
  config:
    activate:
      on-profile: development-omics

rserve:
  environments:
    - name: default
      host: localhost
      port: 6311
    - name: omics
      host: localhost
      port: 6313

datashield:
  profiles:
    - name: default
      environment: default
      whitelist:
        - dsBase
      options:
        datashield:
          seed: 342325352
    - name: omics
      environment: omics
      whitelist:
        - dsBase
        - dsOmics
        - resourcer
        - s3.file.resourcer
      options:
        datashield:
          seed: 712368126

---
spring:
  config:
    activate:
      on-profile: development-exposome

rserve:
  environments:
    - name: default
      host: localhost
      port: 6311
    - name: exposome
      host: localhost
      port: 6312

datashield:
  profiles:
    - name: default
      environment: default
      whitelist:
        - dsBase
      options:
        datashield:
          seed: 342325352
    - name: exposome
      environment: exposome
      whitelist:
        - dsBase
        - dsExposome
      options:
        datashield:
          seed: 039284230

---
# use this profile when you want to run the armadillo within the docker-compose file
spring:
  config:
    activate:
      on-profile: docker-compose

rserve:
  environments:
    - name: default
      host: rserver
      port: 6311
    - name: exposome
      host: rserver-exposome
      port: 6311
    - name: omics
      host: rserver-omics
      port: 6311

datashield:
  profiles:
    - name: default
      environment: default
      whitelist:
        - dsBase
      options:
        datashield:
          seed: 342325352
    - name: exposome
      environment: exposome
      whitelist:
        - dsBase
        - dsExposome
      options:
        datashield:
          seed: 039284230
    - name: omics
      environment: omics
      whitelist:
        - dsBase
        - dsOmics
        - resourcer
        - s3.file.resourcer
      options:
        datashield:
          seed: 93787423
