armadillo:
  # set this to 'true' if you want to accept permissions from oidc provider
  oidc-permission-enabled: false
  # set this true if you want Armadillo to create/edit/delete profile docker images
  docker-management-enabled: true
  # uncomment this to configure a default admin user
  # oidc-admin-user: user@yourdomain.org

  profiles:
    - name: default
      image: datashield/armadillo-rserver
      port: 6311
      package-whitelist:
        - dsBase
      function-blacklist: [ ]
      options:
        datashield:
          # the seed can only be 9 digits
          seed: 342325352
          # foo: bar

springdoc:
  swagger-ui:
    enabled: true
    operationsSorter: alpha
    csrf:
      enabled: true


spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: armadillo
  security:
    user:
      name: admin
      roles:
        - SU

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  forward-headers-strategy: framework
  error:
    include-binding-errors: always
    include-message: always

audit:
  log:
    path: logs/audit.log

logging:
  config: classpath:logback-file.xml

storage:
  root-dir: data
