datashield:
  whitelist:
    - dsBase
springdoc:
  swagger-ui:
    enabled: false

server:
  error:
    include-binding-errors: always
    include-message: always
---
spring:
  profiles: development
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'https://fusion-auth.dev.molgenis.org'
        opaquetoken:
          client-id: '3a1120a3-6e5c-4f14-8cc3-e2c978ac71dc'

minio:
  url: http://localhost
  port: 9000
  access-key: molgenis
  secret-key: molgenis
  userBucket: user
  sharedBucket: shared

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.molgenis: DEBUG
    org:
      springframework:
        web:
          context: DEBUG
---
spring:
  profiles: (development | test)
datashield:
  options:
    nfilter:
      string: 80
      kNN: 3
      tab: 3
      stringShort: 20
      noise: 0.25
      levels: 0.33
      glm: 5
      subset: 3
    datashield:
      privacyLevel: 5
