version: "3.4"
services:
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: molgenis
      MINIO_SECRET_KEY: molgenis
    command: server /data
  datashield:
    build: .
    ports:
      - 3000:8080
  rserver:
    image: obiba/opal-rserver:1.6
    ports:
      - "6311:6311"
      - "6312:6312"
      - "53000-53200:53000-53200"